### ISSUE TITLE
Figure out how to dynamically rendered nested component assets

### ISSUE THREAD

**Issue by pyrello** [uiowa/uids#231]
There is currently a way to define arbitrary data for components using the `meta` property. We can use this property to be able to catalog required asset dependencies for a component, like so:
```yml
# components/prototype/iowa-bar/iowa-bar.config.yml
meta:
  dependencies:
    stylesheets:
      - /components/prototype/logo/logo.css
      - /components/prototype/site-name/site-name.css
      - /components/prototype/parent-site-name/parent-site-name.css
      - /components/prototype/iowa-bar/iowa-bar.css
```
And render this in the preview template:
```twig
{# components/prototype/_preview.twig #}
{% if _target.meta.dependencies.stylesheets is not empty %}
  {% for stylesheet in _target.meta.dependencies.stylesheets %}
    <link media="all" rel="stylesheet" href="{{ stylesheet|path }}">
  {% endfor %}
{% endif %}
```

The downside of this is that we have to maintain manually information that the system already has. Fractal already identifies css, scss, and javascript files inside a component directory as being related to that component. We can already print out the components own assets without having to create these extra records. If we change the location of the component, then we have to go through and update all the dependency records of the components that reference it.

Ideally, these additional dependencies could just be compiled into the components `_target.resources.assets` property along with the components own assets. This would probably require some sort of plugin or manipulation of the process by which Fractal assembles the component record.
